### ISSUE TITLE
When installing module through foundry UI an error occurs

### ISSUE THREAD

**Issue by jjnich** [JDCalvert/FVTT-PF2e-Ranged-Combat#104]
It seems like foundry has the wrong link to the module. The link doesn't include "JDCalvert" and this causes the module to fail to download.

Resolved by manually adding "JDCalvert" between the // after github.com

![image](https://user-images.githubusercontent.com/2105096/213300849-74f1e028-8066-430e-9af9-a60ad10315f7.png)

**Comment by jjnich** [comment]
![image](https://user-images.githubusercontent.com/2105096/213301146-19c918ca-9096-4585-bc28-d00593b8b7f3.png)
Install works with this addition

**Comment by jjnich** [comment]
I apologize if this is just an error on my end, but it seemed very persistent. I pulled the newest foundry version and updated everything I could before finding the very simple workaround.

**Comment by JDCalvert** [comment]
This wasn't you. Somehow I messed up the manifest link on the Foundry website. I've fixed it now, thanks!
