### ISSUE TITLE
Feature Request: Don't consume ammo if weapon isn't able to be fired.

### ISSUE THREAD

**Issue by LebombJames** [JDCalvert/FVTT-PF2e-Ranged-Combat#11]
Currently, even if an actor doesn't have a loaded effect for a given weapon, it'll still consume ammunition upon clicking the strike button. It would be nice if when an actor doesn't have a loaded weapon, that trying to strike doesn't consume that ammo.

**Comment by JDCalvert** [comment]
This is actually an issue with the Pathfinder 2e system that, ironically, I introduced. I can't fix it within the module, but I've opened a merge request with the system to solve it.

This did prompt me to spot that the Loaded effect is still removed if you cancel the attack roll (close the roll dialog) so I've fixed that in 2.0.2.

**Comment by JDCalvert** [comment]
The new release of the Pathfinder 2e system has fixed this issue.
