### ISSUE TITLE
Rule Element Issues with Custom Ammo

### ISSUE THREAD

**Issue by MindWeb125** [JDCalvert/FVTT-PF2e-Ranged-Combat#111]
Hello.

I'm trying to get the Rule Elements working for additional damage on ammunition.

I've copied the element used in the example screenshot for fire damage, which comes out as:

{
    "key": "DamageDice",
    "dieSize": "d6",
    "selector": "{item|data.target}-damage",
    "diceNumber": 1,
    "damageType": "fire"
}

However, when the weapon is fired and the effect rule is generated, it comes out as this:

{
    "key": "DamageDice",
    "dieSize": "d6",
    "selector": "{item|system.target}-damage",
    "diceNumber": 1,
    "damageType": "fire",
    "slug": null,
    "priority": 100,
    "ignored": false,
    "predicate": []
}

And the damage isn't applied on the roll.

![Foundry_Virtual_Tabletop_YDHbi058CU](https://user-images.githubusercontent.com/105242276/219140777-1078ec16-5328-4631-b647-5d4bef64c527.png)

![Foundry_Virtual_Tabletop_PmQiEAG6xQ](https://user-images.githubusercontent.com/105242276/219140879-71de98c0-1150-4de5-8da5-e9cca9fb5850.png)

**Comment by JDCalvert** [comment]
My apologies, the screenshots are out of date after a change in how these sorts of rule elements work in the system. Replace `{item|data.target}-damage` with `{item|flags.pf2e.rulesSelections.weapon}-damage`.

I'll update the screenshots!

**Comment by MindWeb125** [comment]
Aah, I was hoping it wasn't just me messing up something obvious! Thank you!
