### ISSUE TITLE
v10b291 not compatible?

### ISSUE THREAD

**Issue by cleggerama** [JDCalvert/FVTT-PF2e-Ranged-Combat#112]
I got an error on upgrading to the latest build (v10 b291) saying: "PF2e Ranged Combat: Error detected in module. It is likely this module has not been updated for FVTT Version 10. (See JS Console)"

**Comment by JDCalvert** [comment]
Which version of the module do you have? It was updated for v10 a long time ago. A couple of things to try:
* Is the module "locked" from updating? There was a version a _very_ long time ago where I accidentally committed the lock file which stops it from updating.
* Uninstall and reinstall the module. That should get the latest version regardless of what you had before.

**Comment by JDCalvert** [comment]
Closing this as it's been a couple of weeks with no reply.
