### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by DoctorDankovsky** [JDCalvert/FVTT-PF2e-Ranged-Combat#120]
Hello. As a module translator for PF2e, I am very sad to see modules without localization files. I thought about it and decided to give a start in the file attached below, but the module is complex, I'm not a programmer, and I could not figure out how to transfer a line with java script functions to json. But what he could do, he did. It seems to be without errors, but I recommend double-checking.
[pf2e-ranged-combat.zip](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/files/11132740/pf2e-ranged-combat.zip)

**Comment by sakusenerio** [comment]
Seconding for localization needs.
If mods developer allow it, translators can work on localization on Foundry HUD weblate.
Using this website would help a lot, this allows the projects that register on it to generate language files in all languages and makes it easier to maintain them as every change appears allowing the translators to process in real time or almost

https://weblate.foundryvtt-hub.com/

**Comment by JDCalvert** [comment]
I started working on this in #121 (thanks to @DoctorDankovsky for the start). Unfortunately "life" has kept me away from finishing it, but it's on the to-do list!

**Comment by Cuingamehtar** [comment]
@JDCalvert Would you mind if I make an alternative pull request with localization strings? I have a version that should cover all of them (including forms), but my labeling might not be exceptionally consistent.
I just never got around to making the PR.

**Comment by JDCalvert** [comment]
@Cuingamehtar thanks very much for the work you put in. I've now merged all the localisation changes.

@sakusenerio I've registered for Weblate, so hopefully the project will be up soon.
