### ISSUE TITLE
Reloading a has an undefined name

### ISSUE THREAD

**Issue by maplealmond** [JDCalvert/FVTT-PF2e-Ranged-Combat#132]
When reloading a hand crossbow, it will show the name as "undefined".  A screenshot from the chat is attached.

<img width="292" alt="Screenshot 2023-08-04 at 7 50 45 PM" src="https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/22515/665c7c5d-986e-4b6c-bb1f-21844c843fa7">

**Comment by JDCalvert** [comment]
This has been fixed in version 4.0.3, thanks for the report!
