### ISSUE TITLE
hazards when attacking have error messages that dont allow attacks.

### ISSUE THREAD

**Issue by GuitarGuyNick** [JDCalvert/FVTT-PF2e-Ranged-Combat#135]
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/139762764/8e8eb96b-0191-4a54-b13d-a12594ebe3b7)

this happened when i was clicking the attack button on a hazard that had an attack. it refused me to roll.

**Comment by JDCalvert** [comment]
I'm afraid this is not an issue with this module. The error is happening once my module calls back through to normal system code. I'm also not able to reproduce this.

Is it happening without any modules installed? It might be worth re-installing the system.
