### ISSUE TITLE
Player (and GM) can't fire loaded weapon: Says it's unloaded

### ISSUE THREAD

**Issue by fishrobe** [JDCalvert/FVTT-PF2e-Ranged-Combat#137]
As you can see, the module gives the "loaded" icon after loading, but then gives the error that it is not loaded when trying to fire. The gunslinger in my group has 3 guns, and this happens across the board with all of them. It also continues to happen if I give someone else 2 guns and he only has 1 equipped. The guns all have different names, so they are definitely trying to shoot the right ones. I tried it from my (GM) side, but it didn't work for me either.
I ended up turning off the ranged combat module to play our game today. We skipped last week, so I'm not sure when it started, but it worked 2 weeks ago. There was a PF2e rules update since then, but I don't know if that has something to do with it or not. There are no errors in the f12 screen.

Edit: I have also noticed we no longer have the option to load a different gun if one is loaded--it automatically unloads the weapon that was loaded first, before we get a chance to load something else. 

![no load](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/50474856/aede248e-ed2a-42e8-ad16-4d81418cb546)

**Comment by JDCalvert** [comment]
Hi there, sorry it's taken a while to reply to this. Could you post a screenshot of the module's settings please? From the GM's perspective. Then I'll know which code branch might have a problem.

**Comment by fishrobe** [comment]
Hey thanks for getting back. We figured it out. Somehow we'd been using the
"effects" instead of the "macros". Once we switched them it worked again.

Sorry I forgot to update my post.
