### ISSUE TITLE
Auto Destroying when disabled

### ISSUE THREAD

**Issue by Raxoro** [JDCalvert/FVTT-PF2e-Ranged-Combat#139]
Hi, I have the auto destroy toggle turned off for ammo but using reload still removes a bullet whenever fired. I use this mod to help players and me track whether a gun was loaded between turns on not, but I don't track ammo consumption outside of non standard ammo, It would be nice if it was able to check if Auto Destroy was enabled or not before removing ammo.

**Comment by JDCalvert** [comment]
Fixed in 4.0.6.
