### ISSUE TITLE
Hunt Prey Macro does not apply effect to user

### ISSUE THREAD

**Issue by ByronThompson** [JDCalvert/FVTT-PF2e-Ranged-Combat#14]
**Modules Installed:** PF2E Ranged Combat, LibWrapper
**Short Description**: Using the Hunt Prey macro supplied with the module does not apply the effect used to track the user's Hunted Prey. Chat message is still created
**Steps to Recreate**: 
1. Target Creature
2. Use Hunt Prey macro
**Possible Solution**: Using the macro produces this error message
```
Uncaught (in promise) ReferenceError: myActor is not defined
[Detected 1 package: pf2e-ranged-combat]
    at Object.huntPrey (hunt-prey.js:78:5)
```
Looking at line 78 we find this expression
`myActor.createEmbeddedDocuments("Item", effectsToAdd);`
However, `myActor` is never defined within the `huntPrey()` function. changing `myActor `to simply `actor`, like is defined at the beginning of the function may resolve the issue

**Comment by JDCalvert** [comment]
Thanks for the report! Fixed by #15 and released in 2.1.1.
