### ISSUE TITLE
Possibility to add more damage types to Alchemical Crossbow?

### ISSUE THREAD

**Issue by Mortavius** [JDCalvert/FVTT-PF2e-Ranged-Combat#140]
Is there a way to make the Alchemical Crossbow reload work with more energy types?  We have things like the Ghost charge, which deals Vitality (formerly positive) damage or the Necrotic bomb, and those are types of energy damage, according to the Core Rules.

**Comment by JDCalvert** [comment]
Fixed in 4.0.6.
