### ISSUE TITLE
Atlatl not able to accept ammo

### ISSUE THREAD

**Issue by kekeshgreen** [JDCalvert/FVTT-PF2e-Ranged-Combat#141]
Every time the atlatl is loaded the ammo is immediately removed

**Comment by JDCalvert** [comment]
Hi there, I've had a little look at this and it looks like it's working on my end. Could you please let me know which version of Foundry, the PF2e system, and module you are using, as well as what ammunition you are trying to use for the weapon?

Cheers.

**Comment by JDCalvert** [comment]
No reply in a while, so closing.
