### ISSUE TITLE
Fatal trait not working for alchemical shot

### ISSUE THREAD

**Issue by Bladebite** [JDCalvert/FVTT-PF2e-Ranged-Combat#143]
When dealing critical damage using Alchemical Shot with a firearm that has the Fatal trait, the base damage dice do not increase in size.

**Comment by JDCalvert** [comment]
I'm not seeing this, testing with an arquebus.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/38069151/dbba3c82-2716-4c60-a446-6ff2de72a6d0)

Please can you confirm your Foundry, Pathfinder 2e system, and module versions, as well as any replication steps?

**Comment by Bladebite** [comment]
Okay, so I'm using the following versions:
![Foundry version](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/150255733/3c26a7a5-3514-4a7d-be7c-41064a011409)
I was testing with a dueling pistol:
![RangedFatal](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/150255733/5547a0b3-e564-46a0-989c-a4ca7446711a)
Tested arquebuz as well:
![Arquebuz](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/150255733/d1f55b5f-0d25-4bcb-b3ac-2e348571da38)

But didn't work for me. I disabled all other modules to make sure there are no conflicts:
![No modules](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/150255733/c7ea29b4-5c3a-4e0f-b1fe-fef8b8b6cea4)

But still didn't work. 
To fix it for my players I added a base weapon damage size override to d10 when critical hit happens but that's obviously not a very universal solution :)

I'm not sure what info do you need, but I will be happy to provide whatever you request.

**Comment by JDCalvert** [comment]
Closing this as I have been unable to replicate it. If you get this again with a new world, and all Foundry, system, and module versions up to date, please re-open.
