### ISSUE TITLE
Add an option to reload all of the  bullets of a Capacity gun  please!

### ISSUE THREAD

**Issue by Bomberman1988** [JDCalvert/FVTT-PF2e-Ranged-Combat#146]
Reloading capacity weapons is already a pain because you gotta reload one by one, and it doubles the issue when you've to reload 2 Capacity weapons cuz you're using [Paired Shots](https://2e.aonprd.com/Feats.aspx?ID=3168) or [Double Slice](https://2e.aonprd.com/Feats.aspx?ID=356) + [Dual Thrower](https://2e.aonprd.com/Feats.aspx?ID=1951). The only way I found to help me with this is using the macro you created **Reload NPCs**, which reload both weapons, but still one bullet per time, which floods the chat box, so could you please make a macro to reload all of the bullets of a Capacity gun (or both equiped guns) at once?
![flood](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/103781301/3f9c9261-1d62-4f26-8309-95ac0cc4e3a1)

**Comment by Aziareel** [comment]
An off-combat macro to reload all guns a character possesses would be a very nice QoL feature in general.

**Comment by JDCalvert** [comment]
Added the "Fully Reload" macro in 4.1.0 which will perform a full reload of a single weapon. Given how many different messages can happen per weapon, it would be very difficult to automatically reload all weapons. I'll consider this closed for now.
