### ISSUE TITLE
Bug:  If "advanced ammo system" is turned off, firing from a repeating weapon consumes the entire magazine.

### ISSUE THREAD

**Issue by maplealmond** [JDCalvert/FVTT-PF2e-Ranged-Combat#147]
How to reproduce, on a clean world.

* Install PF2e Ranged Combat
* In Options, Deselect Advanced Weapons System
* Give a character a Repeating Crossbow and a few Magazines
* Have character fire the Repeating Crossbow

Instead of removing one charge from the magazine, the entire magazine will be removed.  This only happens when the module is installed.

**Comment by JDCalvert** [comment]
Fixed in 4.0.9
