### ISSUE TITLE
Thunder Sling not allowing the use of darts as ammunition

### ISSUE THREAD

**Issue by DoritoBob** [JDCalvert/FVTT-PF2e-Ranged-Combat#152]
The Tengu weapon (Thunder Sling) uses darts as ammo, even with the darts marked as usable as ammo, when the PF2E Ranged Combat module is on, the darts will not stay assigned to the sling and will not reload either.  Blowgun darts will reload and will assign to it.  I have tried this on several different actors in two different worlds and the same issue occurs.  If I deactivate the module, then the weapon works as intended and allows the loading of the darts of ammo for the Thunder Sling.  Your assistance is greatly appreciated. Screen shot attached

![Screenshot 2024-01-15 at 12 13 59 PM](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/140255307/30b82ed0-8d26-4f25-b997-dc924619ea04)

**Comment by JDCalvert** [comment]
Fixed in 4.2.0.
