### ISSUE TITLE
Reload NPC macro does not work

### ISSUE THREAD

**Issue by dan-gr** [JDCalvert/FVTT-PF2e-Ranged-Combat#155]
in the file utils.js (from ammunition-system), the function 
```
export function checkFullyLoaded(actor, weapon) {
    const weaponFullyLoaded = isFullyLoaded(actor, weapon);
...
```
calls `isFullLoaded `function but this function signature is 
```
export function isLoaded(weapon) {
    const loadedEffect = getEffectFromActor(weapon.actor, LOADED_EFFECT_ID, weapon.id);
...
```
so the first line rises an exception (since the first parameter is actually an actor, not a weapon)

**Comment by JDCalvert** [comment]
Fixed in 4.2.2.
