### ISSUE TITLE
Pf2e Ranged combat: error detected in module(check JS console)

### ISSUE THREAD

**Issue by newelley** [JDCalvert/FVTT-PF2e-Ranged-Combat#158]
Hi there,

Just setting up a new game of Kingmaker (official module) in FoundryVTT and get the above error.  After looking in what i think is the JS console, I have found the following error text:

```
LibWrapperPackageError: Error thrown in hooked function '' for hook 'init'. Error detected in module PF2e Ranged Combat.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat
Report this issue here: https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/issues

== Technical Details:
Detected by libWrapper.
Package ID= pf2e-ranged-combat
Error= Can't wrap 'CONFIG.PF2E.Actor.documentClasses.character.prototype.adjustCarryType', target does not exist or could not be found.

    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at initialiseLibWrapperHooks (libwrapper-hooks.js:17:16)
    at Object.fn (config.js:145:9)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8635:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)`
```
I deactivated all other modules so only this module and libwrapper were active and the result is the same.  I quickly looked through the closed issues and noticed that this error was potentially fixed in 4.2.3, but this is the version I am running.

Happy to supply any other information required to fix this issue, however, the following might be useful:
fvtt version: 11.315
PF2e version: 5.13.1
libwrapper version: 1.12.13.0
web browser: Chrome Version 121.0.6167.140 (Official Build) (64-bit)

I hope you can help!

**Comment by JDCalvert** [comment]
Can you please just double-check the versions? I've just tested with a world with only this module and libWrapper and it was fine.

**Comment by newelley** [comment]
Sure, I will check it tomorrow and report back either way. Thanks for responding 😃

**Comment by newelley** [comment]
Good Morning,

It's super strange, but this morning, the module loaded in fine.  The only thing that changed is that the client PC was switched off overnight.  All the version numbers match those I have written above.  So, sorry to take up your time, and thank you for publishing a great module !
