### ISSUE TITLE
Automate the Precision bonus damage

### ISSUE THREAD

**Issue by xyzzy42** [JDCalvert/FVTT-PF2e-Ranged-Combat#159]
It would nice if the bonus damage from Precision would automatically get added when attacking the Prey and not added when attacking another creature.  While there is the roll option, "1st attack on hunted prey", it has to be manually toggled and doesn't automatically take into account if the target is the prey or not.

The automatically enabled/disabled "hunted-prey" roll option is enough to easily do this.  All that is needed is to add it to the predicate for Precision's DamageDice RE.

But the feat comes from the base pf2e system.

So an idea would be to have this module edit the feat.  It's not that hard to look through the feat's rules, find a damage dice, add "hunted-prey" to the predicate.  It could be done automatically when the feat loads, or there could be a macro one runs to edit the feat.

While one might say, just edit it by hand, there is a large class of players who just aren't going to be able to edit REs by hand.

**Comment by JDCalvert** [comment]
Thanks for pointing this out, I actually never noticed that the feat doesn't take the hunted prey value as a predicate. That sounds like a worthwhile system change, so I'll try to get that updated in the system itself.

For what it's worth, I believe the PF2e Action Support module also handles Hunt Prey and the first attack on hunted prey toggles automatically, so it might be worth looking into that until I get a chance to update the module.

**Comment by xyzzy42** [comment]
Seems like putting it in the system itself would be a layering violation.  The system feat would depend on a roll option, but nothing in the system would provide that option ("hunted-prey").  It's only provided by an external module.

Would certainly makes things easy to do it that way.

There's also an issue trying to get animal companion strikes to get precision.  One can just drag the Precision class feature to the AC's character sheet.  But adding "hunted-prey" to the predicate doesn't work, since that roll option is only automatically set on the ranger's sheet.

But what does work is to add "target:effect:prey-_ranger-name_" to the predicate.  I don't think that can be automated that easily, since there isn't a way to put the ranger name in slug form into the predicate without using a macro to edit it (or just editing the RE manually of course).  There's no link from the AC back to the master (yes, that's a different module), so even something like "target:effect:{actor|system.master.slug}" won't work (also slug isn't a field in actor).

But a macro could edit the feat and inject the properly formatted predicate.

**Comment by JDCalvert** [comment]
I did a rewrite of the Hunt Prey stuff in v5.0.0, and added a way to link the master and companion. Take a look, it should do everything you need for now, including applying the precision edge's damage only on your first damage roll against your prey of the round.

It's not 100% done, but I thought I'd get what I've done out there.
