### ISSUE TITLE
Weapon doesn't use ammo after striking

### ISSUE THREAD

**Issue by Copess** [JDCalvert/FVTT-PF2e-Ranged-Combat#166]
Hi. After the update it looks like when striking with a weapon, the "loaded" effect doesn't go away, and the ammo isn't consumed. I'll gladly give any more help or info. 

Thanks in advance,

Using PF2e Ranged combat v5.1.1, foundry v11 stable 315 and pathfinder 2e 5.14.1
The module settings (configured in game settings) are all the boxes true, minimum permission "none" and hide token effects false

**Comment by JDCalvert** [comment]
This is caused by the system changing its weapon's `requiresAmmunition` function to `ammoRequired`. This caused the module to not know that any weapon required ammunition, so everything around using ammunition was skipped.

I'll have a fix out soon.

**Comment by JDCalvert** [comment]
This should now be fixed.
