### ISSUE TITLE
pf2e Ranged Combat not unloading weapon

### ISSUE THREAD

**Issue by TheRealJohnnySteele** [JDCalvert/FVTT-PF2e-Ranged-Combat#167]
Hello, recently it stopped working. Last Friday if a player fired a weapon with a reload of 1, it would unload the weapon and the player would have to spend an action to reload. Now it doesn't unload. Created a new, empty, pf2e game with no modules except pf2e Ranged Combat and it does not unload the weapon, so I don't think it's anything on my end.

**Comment by JDCalvert** [comment]
Duplicate of #166, will handle this there.
