### ISSUE TITLE
Loaded condition not removed when firing dueling pistol

### ISSUE THREAD

**Issue by BalrogTaco** [JDCalvert/FVTT-PF2e-Ranged-Combat#168]
Hello,

I am using the latest Pf2E system (5.14.3) and Ranged-Combat module(5.1.1).  Every time the gunslinger in my game fires their dueling pistol, the loaded condition is not removed.  I also tested with a crossbow with the same result.

Also ammunition that is selected does not seem to recognize - Rounds (Dueling Pistol) and the player is prompted every time they use the reload macro to pick the ammunition.  The "Set as Ammunition" checkbox does not change this.  The ammunition is set on the actions tab of the player sheet.

I do not see an errors or warning in the console

**Comment by JDCalvert** [comment]
This should be fixed in 5.1.2.

**Comment by BalrogTaco** [comment]
verified fixed
