### ISSUE TITLE
[Bug] Ammunition Not Being Consumed

### ISSUE THREAD

**Issue by 117ksk** [JDCalvert/FVTT-PF2e-Ranged-Combat#170]
As of PF2e system update 5.14.0, ammunition will no longer get consumed when ranged strikes with ammo attached are completed. This occurs to all ranged strikes regardless of PF2e Ranged Combat settings. Ammo will only be consumed on strikes if this module is not active. No errors can be found in the console.

**Comment by JDCalvert** [comment]
This should have been fixed in the new release of this module last night. Could you check if the bug still happens on the latest version please?

**Comment by 117ksk** [comment]
Yes, this issue is now fixed! After updating to v5.1.2, ammo is now consumed as expected. Thank you!
