### ISSUE TITLE
[Bug] Hunt Prey Not Automatically Applying Roll Option

### ISSUE THREAD

**Issue by 117ksk** [JDCalvert/FVTT-PF2e-Ranged-Combat#171]
When the Hunt Prey macro is used, the "Target is your Hunted Prey" Roll Option RE is not automatically enabled despite target having the "Prey" effect. Only after un-targeting the prey and re-targeting again will the Roll Option trigger.

https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/113755707/2a891451-124f-4fd5-a946-1c1abaad0173

**Comment by JDCalvert** [comment]
This should be fixed in 5.1.3.
