### ISSUE TITLE
Advanced Ammunition System + PF2e System prevents firing a loaded round if it's your last round

### ISSUE THREAD

**Issue by dcoffee** [JDCalvert/FVTT-PF2e-Ranged-Combat#174]
Using PF2e System 5.14.4 and Ranged Combat 5.1.3:

Using Advanced Ammunition System, when I load the final round of an ammunition into a Gun Sword, so that the PF2e System ammunition dropdown reads as 0 rounds, the System prevents me from Striking with the weapon from the weapon strikes section of the Actions tab of an Actor sheet, with a warning of "No ammunition is assigned to Gun Sword. Check the Actions tab of [Actor]'s sheet."

Disabling Advanced Ammunition System fixes this issue but I lose the benefit of tracking my loaded round via an effect.  Also, as a corollary, if I change the ammo dropdown to another ammo type with 0 rounds remaining, it stops the gun from Striking despite having a different round "loaded," even if the loaded ammo type has reserves.

![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/40677907/8b8079b5-3d90-4a5c-9d9a-e6692581c208)

**Comment by fraserstanton** [comment]
I have this same issue, nothing fancy needed to cause it, just have no ammo in your inventory and one in the chamber and it won't let you fire.
