### ISSUE TITLE
Advanced Ammunition System + PF2e System: Ammo Rule Elements

### ISSUE THREAD

**Issue by dcoffee** [JDCalvert/FVTT-PF2e-Ranged-Combat#175]
Rule elements on ammo types seem to apply based on the PF2e System ammunition dropdown on the Actions tab of an Actor sheet, rather than the Loaded - [Ammo Type] effect used with the Advanced Ammunition System.

For example, If I select a normal Round and Reload it (via macro or the Actions tab button), but then swap ammo types to Explosive Ammunition, my buff effect will still say Loaded - Round, but upon Striking, will trigger the Rule Elements of Explosive Ammunition.

It'd be nice if there were a convenient way to save a reference to the loaded ammo's rule elements and apply them when fired, rather than relying on whatever is selected in the dropdown at the time.

**Comment by JDCalvert** [comment]
I've disabled the system's ammunition effect handling and re-introduced an improved version of the module's ammunition effect handling in 5.3.0.
