### ISSUE TITLE
There's no way to turn off the chat messages that a character fired an arrow

### ISSUE THREAD

**Issue by OutlandishVillainy** [JDCalvert/FVTT-PF2e-Ranged-Combat#178]
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/93902659/89181523-d47b-47b8-9979-0407dd3b9491)
There's no setting to turn off these messages whenever a character fires a piece of ammunition.

**Comment by JDCalvert** [comment]
I've added more options to control these messages in 5.2.0.
