### ISSUE TITLE
Wrong text label and description

### ISSUE THREAD

**Issue by Lioheart** [JDCalvert/FVTT-PF2e-Ranged-Combat#179]
Wrong label and description in Effect: Crossbow Crack Shot

![obraz](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/39154364/6864381c-5ad9-4bfb-93e5-ff6cd5cd957c)

**Comment by JDCalvert** [comment]
Fixed in 5.3.0.
