### ISSUE TITLE
Ammunition rule elements still ignored in 6.2.1

### ISSUE THREAD

**Issue by johncarney** [JDCalvert/FVTT-PF2e-Ranged-Combat#184]
Issue #183 was reported as fixed in version 6.2.1 of _PD2e Ranged Combat_, but ammunition rule elements are still ignored. The problem is illustrated in the video below.

https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/322950/a8b68ac9-9d04-44eb-961e-e6e99e12b1ae

**Comment by TheGnome1** [comment]
just tested ... if you actually Fire the arrow and roll damage from attack card it works... just trying to roll damage from the sheet will not work however.

**Comment by johncarney** [comment]
> just tested ... if you actually Fire the arrow and roll damage from attack card it works... just trying to roll damage from the sheet will not work however.

Aha. Thanks. So it's a workable fix, though it would be nice if rolling damage from the actions tab would work as well.

**Comment by JDCalvert** [comment]
My apologies, I should have explained that in the previous issue!

In the module's implementation of ammunition effects, the effect is applied when you fire and is then removed when you roll damage (or fire again). This is changed from the system's implementation to fix #175.

I think the best way around this is likely an option to revert to the system's implementation (so you can change ammunition type between firing and damaging) and a warning if rolling damage with ammunition selected that doesn't match the effect currently applied.

**Comment by johncarney** [comment]
Thanks for the explanation. Given that rolling damage without a preceding strike, or changing ammo after a strike are rare use-cases, I'm happy with things as they stand.

If it's possible, a simple warning that things may not work the way the user expects would be great. An option to work around would be the cherry on top.

In any case, thanks for your prompt responses to all of this. _PF2e Ranged Combat_ is a must-have module for me both as a player and a GM and going in to a campaign where I wanted to use cold iron or silver ammunition, having to choose between that and the module was a terrible dilemma 🙃

Thanks for your excellent work.

**Comment by johncarney** [comment]
PS. I'm working on a basic compendium module with a variety of precious material ammunition. If you're interested in using it for testing purposes, I'll let you know when it's ready.

**Comment by JDCalvert** [comment]
I've added warnings and an option to disable the ammunition effects system and revert to the system's implementation.

@johncarney that compendium sounds great, I'd love to see it when it's done!

**Comment by johncarney** [comment]
Awesome. Works a treat. Thanks :)

**Comment by johncarney** [comment]
I have a few things on my plate right now, but I should have the compendium up in a week or so.

**Comment by johncarney** [comment]
> @johncarney that compendium sounds great, I'd love to see it when it's done!

[Prisha's Precious Projectiles](https://github.com/johncarney/prishas-precious-projectiles) is now up on Github. I consider this a private beta, so please do not share.

There are installation instructions and caveats on the Github page.
