### ISSUE TITLE
Ammunition effect warning is always shown

### ISSUE THREAD

**Issue by johncarney** [JDCalvert/FVTT-PF2e-Ranged-Combat#187]
When rolling damage for a projectile weapon, the ammunition effect warning is always shown even when there has been a preceding strike. It is also shown regardless of whether the ammunition has any rule elements or not.

The attached videos demonstrate the problem for regular ammunition and cold iron ammunition.

## Steps to reproduce

1. Create a world with a simple battle map and activate the **PF2e Ranged Combat** module
2. Create an actor and equip them with a longbow and arrows
3. Draw the longbow and set its ammunition to the arrows
4. Place the actor and an NPC on to the battle map
5. Select the actor and target the NPC
6. Strike with the longbow
7. Roll the damage from the attack card
8. It should just roll the damage, but it rolls the damage AND displays an ammunition effect warning.

## Demonstration with regular ammunition

https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/322950/38b271fc-d61c-459b-b2a0-70367862a697

## Demonstration with cold iron ammunition

https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/322950/e0fefa0e-9c26-45e3-b9a1-7c003f8a3bb9

**Comment by JDCalvert** [comment]
This should be fixed in 6.3.1.

**Comment by johncarney** [comment]
Looks good. Thanks.

I am seeing some unexpected behaviour around repeating crossbow magazines, but that may just be me not being familiar with your loading/unloading system. In any case, I'm not seeing the effects warning and the material type is being applied correctly.
