### ISSUE TITLE
Module seems to be intefering with the Substitute Roll Rule Element from Devise-A-Stratagem

### ISSUE THREAD

**Issue by liquidsonic** [JDCalvert/FVTT-PF2e-Ranged-Combat#188]
Hi! The last update seems to be intefering with the Devise-A-Stratagem roll somehow according to the soft warning in the console.

I QAed it through Find The Culprit.

![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/18706361/f3d3c448-3cb1-4c8e-b9ae-bc3cddfa2df1)

**Comment by JDCalvert** [comment]
Fixed in 6.3.2
