### ISSUE TITLE
Bug: Ranged combat is not respecting strikes rolled with `consumeAmmo: false`

### ISSUE THREAD

**Issue by esheyw** [JDCalvert/FVTT-PF2e-Ranged-Combat#193]
I'm writing a macro + effects solution for [Fake Out](https://2e.aonprd.com/Feats.aspx?ID=3161) ( [my solution](https://github.com/esheyw/pf2e-guides/wiki/Fake-Out-solution) ), and as per the PFS note it does not consume ammo. The system has something for this:
```js
//roll the first held weapon at map 0 without consuming ammo
actor.system.actions[0].variants[0].roll({consumeAmmo: false})
```
This works fine without Ranged Combat, but with it it complains about loading and still consumes the ammo after the strike, disregarding the passed option.

edit: I see that there's supposed to be some Fake Out automation in the module already, but I can't find it (I was writing this as a #macro-polo request, I don't gunslinger myself). Regardless this is still a bug, I think.

**Comment by JDCalvert** [comment]
I managed to figure out a way round this in 6.3.5. It looks like it works fine in both v11 and v12, so let me know if you have problems!
