### ISSUE TITLE
v12 Support

### ISSUE THREAD

**Issue by Peach774** [JDCalvert/FVTT-PF2e-Ranged-Combat#194]
I've been using v12 for a bit now and it seems like embedded reloads aren't working. IE Raconteur's reload doesn't cause the macro to fire and give the buff

**Comment by JDCalvert** [comment]
The module doesn't have any support for actions which are effectively "do one thing and then do another". You have to do the things separately in some way supported by the module, e.g. for Raconteur's Reload, reload the weapon using the reload macro (or the reload button near the Strike on the character sheet), and then Create a Diversion or Demoralize in the usual ways.
