### ISSUE TITLE
Using the hunt prey macro turns off "Target is your Hunted Prey" toggle. 

### ISSUE THREAD

**Issue by Kiingy** [JDCalvert/FVTT-PF2e-Ranged-Combat#197]
Hi,

The hunt prey macro will turn off the toggle displayed under the Actions > Encounter character sheet tab whenever it's used and you have to manually turn it back on, each time, otherwise no effects from hitting the hunted prey will trigger, so the rangers edge effects, the reduced MAP and the hunter's anthem bow effect will not trigger.

**Comment by JDCalvert** [comment]
The module does not use the checkbox to determine whether or not to apply the various effects of Hunt Prey. The "hunt-prey" roll option is added to the roll if you're targeting your hunted prey when making the roll.

I left the tickbox there (and it will work as normal) for times when the hunted prey is not targetable e.g. tracking a prey, so they aren't on the map.

**Comment by Kiingy** [comment]
Is there a way it could be configurable to toggle that checkbox on after using the hunt prey macro?

The most common use case I see for my players is they'll mark a target on the map as hunted prey, then will strike from a hotbar item macro or use an eldritch shot macro. Rolling from these wont apply the hunted prey affect unless they manually toggle the checkbox from the action tab, which is getting reset every time they change prey.

**Comment by Kiingy** [comment]
So on further testing. It won't correctly adjust the MAPs when a strike is done (on a flurry ranger) from a hot bar macro and the Hunt Prey interaction on the Hunter's Anthem bow (the remastered Oathbow) does not function at all, you must manually toggle the "Target is your Hunted prey" checkbox for them to work.

The Precision damage from the precision ranger does work correctly. 

This is the bow.
https://2e.aonprd.com/Equipment.aspx?ID=2867
