### ISSUE TITLE
Error due to not properly Libwrapping

### ISSUE THREAD

**Issue by ChasarooniZ** [JDCalvert/FVTT-PF2e-Ranged-Combat#198]
![image](https://github.com/user-attachments/assets/8db0000e-db74-4558-98f2-5011a7d4897e)

**Comment by 7H3LaughingMan** [comment]
This is a warning and not an error, it occurs when trying to fire a non-loaded weapon which makes sense because PF2e Ranged Combat is preventing the attack roll.

**Comment by JDCalvert** [comment]
I agree. After some testing it all looks like it's working correctly. For best results, I'd say put Ranged Combat as a higher priority in libWrapper compared to Perception. That way, if you try to fire without ammunition (or for any other reason that Ranged Combat will cancel the attack) then Perception won't bother rolling the flat check.
