### ISSUE TITLE
Gunslinger Support

### ISSUE THREAD

**Issue by jadrian2006** [JDCalvert/FVTT-PF2e-Ranged-Combat#24]
When I went to try this module with Gunslinger, my guns would not reload with the macro.

It would be very cool to add macro/actions for each of the gunslinger reload abilities. 

Reloading Strike for example.

**Comment by JDCalvert** [comment]
After looking through the slingers reloads, I'm afraid I don't think this isn't really in scope for the module. Each of the actions is basically just two actions for the price of one, and with the various conditions on them it would be a pretty significant amount of work to implement for, I think, not very much gain.

For the simplest ones, like Reloading Strike, you could probably make a macro that calls the "reload" action from this module (see the Reload macro for how to do this) and then rolls a strike for whatever melee weapon you're holding. But for some of the other ones, it'll probably be easier just to read out/post the action and then resolve the actions separately.

Thank you so much for using the module, and for the suggestion. I'm sorry that it won't make it in at the moment.
