### ISSUE TITLE
Permission-based Reload Chat Messages

### ISSUE THREAD

**Issue by jocolamarco** [JDCalvert/FVTT-PF2e-Ranged-Combat#31]
Currently, whenever the GM uses the macro to reload the npc weapons, it displays the following message for everyone to see:
![image](https://user-images.githubusercontent.com/45291719/160627270-5c6645d6-ca60-4fbe-9075-6e1326ef2640.png)

Ideally, it should be possible to hide the messages from players.

**Comment by JDCalvert** [comment]
I've just released version 2.4.0 which adds an option to only let players see these messages if they have at least the permission level set in module settings. I hope it covers what you need!
