### ISSUE TITLE
[FEATURE REQUEST] Ammunition Consumed Description

### ISSUE THREAD

**Issue by pereiraoc** [JDCalvert/FVTT-PF2e-Ranged-Combat#32]
Hey, thanks for implementing the alchemical crossbow!

I want to use different and custom ammunitions (extra fire damage por example).
Could you implement a chat message declaring the ammunition used (description of the item) when the ammunition is used?
That way I can use a [[/r 1d6]] in the description to apply the extra damage.

:)

**Comment by JDCalvert** [comment]
This has been released in v2.3.0. I've also gone one step further and allowed you to add effects to your ammunition that take effect when you fire it. See the ReadMe for an example of how it works!
