### ISSUE TITLE
Support for multi-barreled weapons

### ISSUE THREAD

**Issue by Ro4m3r** [JDCalvert/FVTT-PF2e-Ranged-Combat#35]
Support for multi-barreled weapons (capacity-3, capacity-4, capacity-5, double-barrel traits) would be really nice.

I'm not sure what the best way to achieve this would be. 

Double Barrel would probably be the easiest, with each barrel just showing up separately when reloading and firing (if the barrel is loaded), just as if it was two separate guns.

Capacity would probably either require a separate prompt when reloading to switch barrel instead of reloading a barrel, or have a separate macro for the 1 action interact to swap barrel? Not entirely sure on this one.

**Comment by JDCalvert** [comment]
I've just released 2.4.0 which handles both capacity and double barrel weapons.

The only part that I cannot yet cover is allowing both barrels of a double barrel weapon to be fired at once. That requires a small change to the Pathfinder 2e system.

**Comment by JDCalvert** [comment]
Finally released in 2.6.0!

**Comment by Ro4m3r** [comment]
> Finally released in 2.6.0!

Awesome! Just played around with it and really loving it, makes using capacity weapons much easier. 
There's a few more things missing from RAW, I'll open a new issue for them.
