### ISSUE TITLE
Version Update Problem

### ISSUE THREAD

**Issue by Armandeus66** [JDCalvert/FVTT-PF2e-Ranged-Combat#39]
At version 2.3.0 Foundry asks to update the manifest link. I click yes. It proceeds and shows this module as updated, but shows "2.3.0-2.3.0" as the update.
The next time it also asks to update the manifest and updates to the same version, never getting to 2.3.1.

**Comment by r-valyar** [comment]
I confirm this bug and add the following:
If I uninstall the module and install it back, the version remains 2.3.0 rather than 2.3.1 as stated in the "Install Module" window.

![image](https://user-images.githubusercontent.com/63558984/163665749-3aa4f63b-9d62-4a96-b7d2-039041532ccb.png)

**Comment by JDCalvert** [comment]
@Armandeus66 and @r-valyar I think I've managed to fix the problem. Please try to update again. Hopefully I've fixed it for the future as well, but we'll have to wait until the next update for that.

**Comment by r-valyar** [comment]
@JDCalvert  looks good now! :)

**Comment by JDCalvert** [comment]
Just pushed 2.3.2 and confirmed that the update worked fine. Closing this.
