### ISSUE TITLE
Sprite ranged strike wont work with this module

### ISSUE THREAD

**Issue by viniciusaraujo093** [JDCalvert/FVTT-PF2e-Ranged-Combat#41]
When tried to strike with Luminous Spark, the module shows a dialog with info 'You cannot fire this weapon because no ammo is selected', but with or without ammo the error occurs.

![image](https://user-images.githubusercontent.com/57771177/164243854-3742a16b-6a4d-4727-b0f2-e7df9534f9a8.png)

![image](https://user-images.githubusercontent.com/57771177/164244369-07d42f0b-aadb-4776-836b-61f5f3468250.png)

**Comment by JDCalvert** [comment]
Thanks for the report. This should be an easy fix, expect it within the next few hours.
