### ISSUE TITLE
Reloading Firearms results in Round count going negative and becoming unusable. 

### ISSUE THREAD

**Issue by TehT** [JDCalvert/FVTT-PF2e-Ranged-Combat#56]
When reloading an arquebus using the Reload macro, the count on the selected ammo type becomes [object Object] until quantity is increased, this also removes the round from the active weapon, resulting in it being unfireable until fixed . 
![Foundry_Virtual_Tabletop_xazPSvj26d](https://user-images.githubusercontent.com/7915544/172227489-2fa2a7ac-d5e2-4178-90bf-c0967bc5c2ed.png)

**Comment by JDCalvert** [comment]
Hi, thanks for the report. I haven't been able to replicate this issue myself, could you provide some information please?
* The Pathfinder 2e system version you're using (on the settings tab)
* The version of the module you're using

At some point in the past, the data structure in the system changed, and caused this issue with the module, but was fixed a while ago. However, depending on the versions you have, the issue could occur for you.

**Comment by TehT** [comment]
Aha! that was the solution, thank you! I thought I had everything up to date as I had checked for updates on both system and addons. However it seems that for some reason i had this module locked at an earlier version! I updated now and checked it and it works as advertised now! thanks for the quick response and thanks for the module!

**Comment by JDCalvert** [comment]
That may actually have been my fault as well, I included the module.lock file in one of the releases!
