### ISSUE TITLE
Alchemical Bomb damage cannot be rolled from chat card when Advanced Thrown Weapon System is Enabled

### ISSUE THREAD

**Issue by patcharapon-j** [JDCalvert/FVTT-PF2e-Ranged-Combat#67]
# Reproduction Steps
1. Enable `Advanced Thrown Weapon System`
2. Make a strike with an alchemical bomb (ex. Junk Bomb)
3. Tap damage button in the chat card to roll damage.
# Results
## Expected
The damage is rolled and damage chat card is shown
## Actual
Nothing Happens, the damage can be rolled again when the bomb is drawn again.
# Proof
https://user-images.githubusercontent.com/15208087/176956640-e6234be6-ca72-48b5-bfee-24ddd5f4f7b5.mp4
# Environment
- Foundry Version `9.269`
- PF2e Version `3.12.2.10`

**Comment by JDCalvert** [comment]
Hmm, this seems to be a fundamental flaw with the whole advanced thrown weapon system. I didn't think that the damage buttons would depend on the weapon being drawn, but I clearly didn't test it either. This will need an entire rework of the system - probably something similar to the reloading system for ranged weapons that use ammunition.

Thank you for reporting this - I'll do my best to fix the issue but in the meantime, I'm afraid the only thing I can recommend is to disable the advanced thrown weapon system.

**Comment by patcharapon-j** [comment]
Okay! happy to help. This module is really awesome!

**Comment by JDCalvert** [comment]
I've released 2.8.3 with a complete rework of the Advanced Thrown Weapon system. I think it's much better now. I was very keen not to rely on effects for this one.
