### ISSUE TITLE
Bug: Hunt Prey Macro

### ISSUE THREAD

**Issue by roguedevjake** [JDCalvert/FVTT-PF2e-Ranged-Combat#68]
Doesn't seem to be triggering the benefit against the targeted enemy anymore, at least for flurry

**Comment by JDCalvert** [comment]
I've tested this with the latest version of both the module and the PF2e system. This appears to be working correctly.

Just to check - do you either have the character hunting prey selected _or_ is that your assigned character? Also, the hunted prey must be your _only_ target. It won't work if you target multiple tokens.

**Comment by roguedevjake** [comment]
@JDCalvert Yeah it works, turns out foundry hadn't migrated the character properly during an update. Deleting the hunt prey feature and replacing it with one from the compendium got it working as it should.
Should have been my first port of call since the january update broke the barbarian's rage -laughs- 

Sorry for the false alarm.

**Comment by JDCalvert** [comment]
No problem. It was probably my change to the system that caused the issue, I moved all the hunted prey stuff to the action from the feature, so everything else that granted the action would work the same way. I'll glad it's working now!
