### ISSUE TITLE
Feature Request: Support for Alchemical Shot

### ISSUE THREAD

**Issue by eboyle1017** [JDCalvert/FVTT-PF2e-Ranged-Combat#72]
Similar in function to Alchemical Crossbows, is it possible to support the gunslinger feat Alchemical Shot? A macro could load a bomb into a crossbow or firearm, and changes the weapon's entire damage type to that bomb for one shot, as well as post a Persistent Damage effect of that type. It also can also damage the user if they miss, but this last part might be out of scope for this mod.

https://2e.aonprd.com/Feats.aspx?ID=3165

**Comment by JDCalvert** [comment]
This has been released in 2.9.0!
