### ISSUE TITLE
Foundry Vtt V10 Compatibility

### ISSUE THREAD

**Issue by medeiros961030** [JDCalvert/FVTT-PF2e-Ranged-Combat#80]
hello, are you going to integrate your module to the foundry V10?

**Comment by JDCalvert** [comment]
Yes, although I'm waiting for a stable release of the PF2e system before I do so. I haven't yet checked whether there are any compatibility issues with V10. If I'm lucky, everything will "just work".

**Comment by JDCalvert** [comment]
Version 3.0.0 is released which v10 compatibility.
