### ISSUE TITLE
Feature Request: Changing ammunition type

### ISSUE THREAD

**Issue by Sparkasaurusmex** [JDCalvert/FVTT-PF2e-Ranged-Combat#82]
A dialogue to choose from various types of ammunition.  For example a blow gun user who has regular and poisoned darts.

**Comment by Sparkasaurusmex** [comment]
A macro would work.  I want it as you say, another click at the point of reloading, but a separate macro would work just as well (I could simply combine them for my use case).

My player makes poisoned blowgun darts, and must change them via the character sheet all the time.  Even another click during reloading would save some effort.  We love what the module does for now, but he asked me if I could add that feature, which I cannot figure out how to do.

**Comment by JDCalvert** [comment]
I'm re-opening this as I intend to have a way of popping up the ammunition selection on reload.

**Comment by JDCalvert** [comment]
These extra features have been released in version 3.2.0.
