### ISSUE TITLE
[Requests] Double Prey & Hunt Prey effect

### ISSUE THREAD

**Issue by JerkyGunner** [JDCalvert/FVTT-PF2e-Ranged-Combat#84]
The ranger's Double Prey feat allows the ranger to pick two "prey" targets and I believe currently the macro will not allow more than one prey per character.

In addition, it would be helpful if designating something as a Hunt Prey target gave it a visible effect icon as this would allow it/them to be distinguished if they're part of an encounter with multiple versions of the same enemy etc.

**Comment by JDCalvert** [comment]
I've implemented Double Prey and Triple Threat in release 3.2.0. Although I'd love to show something on the hunted prey itself, this would require some very fancy code to route through the GM client (players can't alter unowned tokens), which I don't have the time to even look at at the moment.

I've heard on the grapevine that something related to this may come to the Pathfinder 2e system in the future. If it does, I'll make sure the module is updated to utilise it!
