### ISSUE TITLE
bug with magazine

### ISSUE THREAD

**Issue by medeiros961030** [JDCalvert/FVTT-PF2e-Ranged-Combat#85]
When I have the "ranged combat macros" module disabled, my attacks normally consume bullets (5bullets)
![image](https://user-images.githubusercontent.com/112792783/192431016-805bea32-7cfd-498a-8cb0-f70282e0d825.png)

But when I activate your module, the game consumes my number of magazines (4magazines in this case)
![image](https://user-images.githubusercontent.com/112792783/192431284-91f9075d-bd87-4d93-94cc-bd03f99a97bd.png)

When I have the option below unchecked, it consumes my magazines, as I reported, and I can't use any reload macros
![image](https://user-images.githubusercontent.com/112792783/192431402-3411d54e-e95e-46c3-96f1-a0e7ea86fe76.png)

I try to use reload magazine macro, and I get this error:
![image](https://user-images.githubusercontent.com/112792783/192431660-e7c3dc6c-3ac4-4fe6-8e78-3f0755148771.png)

Then when I activate this "advanced anumition system" I can't shoot because this error appears:
![image](https://user-images.githubusercontent.com/112792783/192431713-9613363e-65c7-4e65-b026-67d4f1476b26.png)

And then when I try to use the "Reload magazine" macro, this error appears:
![image](https://user-images.githubusercontent.com/112792783/192431907-42009557-3267-4b27-94ca-1de91e74e437.png)

**Comment by JDCalvert** [comment]
Thanks for the report. Can I please check the versions you're using of:
- Foundry
- Pathfinder 2e system
- PF2e Ranged Combat module

**Comment by medeiros961030** [comment]
Version PF2e : 4.1.3 (latest)
Version Foundry: 10 Build 246 (Latest)
Version Module: 3.1.0 (Latest)

**Comment by JDCalvert** [comment]
Thanks, it must be an issue with the v10 data structure changes. Hopefully will be fixed this weekend.

Until then, I'm afraid I have no workaround other than to disable the module for the time being.

**Comment by medeiros961030** [comment]
No problem, I'll do that. Check the compatibility with the other modules, and the error persisted when I had only activated Ranged combat (and its dependencies) and the foundry, so that's probably the case.

Thanks for listening!
