### ISSUE TITLE
[Feature Request] Thrown and consumable trait

### ISSUE THREAD

**Issue by roguedevjake** [JDCalvert/FVTT-PF2e-Ranged-Combat#92]
When throwing a weapon that has the consumable trait (bombs, holywater, etc) can the drop to the ground option be made to ignore the weapon? 

(My party's alchemist was driving himself mad -laughs-)

**Comment by JDCalvert** [comment]
Could you clarify this a little please? At the moment, consumables shouldn't drop but be destroyed on use. However, when the "advanced thrown weapon system", only one bomb is drawn at a time, so throwing it removes the only drawn one, requiring another to be drawn to throw again.

I'm guessing your alchemist has quick bomber or something similar, and it's a pain to draw one each time when it shouldn't cost an action?

**Comment by JDCalvert** [comment]
Since this has been open a few weeks without an update, I'll close it for now.
